repos:
-   repo: https://github.com/RandyBrown12/Provider_Vault.git
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
default_language_version:
  python: python3.13.1