repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-illegal-windows-names
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: check-docstring-first
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.13.1
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
default_language_version:
  python: python3.13.1
