repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-illegal-windows-names
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args: ["--branch", "main"]
    -   id: requirements-txt-fixer
    -   id: check-docstring-first
default_language_version:
  python: python3.13.1
