name: GitHub Workflow to Perform Testing.

env:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres # pragma: allowlist secret
  DB_NAME: postgres

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  RunTests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code from this repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          python -m pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
      - name: Add Env File
        run: |
          cp .env.template .env
          SAFE_DJANGO_SECRET_KEY=$(echo "$DJANGO_SECRET_KEY" | sed 's/"/\\"/g')
          sed -i 's/SECRET_KEY=""/SECRET_KEY=$DJANGO_SECRET_KEY/g' .env
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      - name: Add Chrome with Driver
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
      - name: Test connection
        run: |
          psql -h localhost -U postgres -d postgres -c '\conninfo'
      - name: Run Tests
        run: |
          source .venv/bin/activate
          python manage.py test
        env:
          ENVIRONMENT_STAGE: TEST
